// Generated by scripts/generate-remittance-batch-edge.mjs; edit the source.
import {
  normalizeRemittanceInput,
  PayrollRemittanceError,
  type RemittanceInput,
  type RemittanceProjection,
} from "./payroll-remittance-marker-core.ts";

export const REMITTANCE_BATCH_MAX = 10;
export const REMITTANCE_BATCH_CONCURRENCY = 3;
export interface RemittanceBatch {
  weekStart: string;
  markers: RemittanceProjection[];
}

/** Validate the whole bounded query before starting any item reads. */
export function remittanceBatchQuery(
  search: URLSearchParams,
): RemittanceInput[] {
  for (const key of search.keys()) {
    if (
      !["maidProfileIds", "weekStart"].includes(key) ||
      search.getAll(key).length !== 1
    ) throw new PayrollRemittanceError("VALIDATION_ERROR");
  }
  const ids = search.get("maidProfileIds");
  if (!ids || ids.length > REMITTANCE_BATCH_MAX * 37 - 1) {
    throw new PayrollRemittanceError("VALIDATION_ERROR");
  }
  const inputs = ids.split(",").map((maidProfileId) =>
    normalizeRemittanceInput({
      maidProfileId,
      weekStart: search.get("weekStart"),
    })
  );
  if (
    inputs.length > REMITTANCE_BATCH_MAX ||
    new Set(inputs.map((input) => input.maidProfileId)).size !== inputs.length
  ) throw new PayrollRemittanceError("VALIDATION_ERROR");
  return inputs;
}

/** Not a cross-item DB snapshot. Each read retains live session/scope validation. */
export async function readRemittanceBatch(
  actor: { profileId: string; role: string; mustChangePassword: boolean },
  search: URLSearchParams,
  read: (input: RemittanceInput) => Promise<RemittanceProjection>,
): Promise<RemittanceBatch> {
  if (actor.mustChangePassword) {
    throw new PayrollRemittanceError("PASSWORD_CHANGE_REQUIRED");
  }
  if (actor.role !== "admin" && actor.role !== "maid") {
    throw new PayrollRemittanceError("PAYROLL_ACCESS_REQUIRED");
  }
  const inputs = remittanceBatchQuery(search);
  const first = inputs[0];
  if (!first) throw new PayrollRemittanceError("VALIDATION_ERROR");
  if (
    actor.role === "maid" &&
    inputs.some((input) =>
      input.maidProfileId !== actor.profileId.toLowerCase()
    )
  ) throw new PayrollRemittanceError("PAYROLL_ACCESS_REQUIRED");
  const markers = new Array<RemittanceProjection>(inputs.length);
  let next = 0;
  let failed = false;
  let failure: unknown;
  async function worker() {
    while (!failed && next < inputs.length) {
      const index = next++;
      const input = inputs[index];
      if (!input) return;
      try {
        markers[index] = await read(input);
      } catch (error) {
        if (!failed) {
          failed = true;
          failure = error;
        }
      }
    }
  }
  // Drain already-running reads before propagating failure; never return partial data.
  await Promise.all(
    Array.from({
      length: Math.min(REMITTANCE_BATCH_CONCURRENCY, inputs.length),
    }, worker),
  );
  if (failed) throw failure;
  return { weekStart: first.weekStart, markers };
}
