// Generated from src/modules/post-approval-room-issues/post-approval-room-issue.routes.ts. DO NOT EDIT.
export const postApprovalRoomIssueHttpErrorStatuses: Readonly<
  Record<string, number>
> = Object.freeze({
  VALIDATION_ERROR: 400,
  INVALID_POST_APPROVAL_ROOM_ISSUE: 400,
  MISSING_ACCESS_TOKEN: 401,
  INVALID_ACCESS_TOKEN: 401,
  PROFILE_NOT_FOUND: 401,
  SESSION_REVOKED: 401,
  ADMIN_REQUIRED: 403,
  PASSWORD_CHANGE_REQUIRED: 403,
  ACCOUNT_INACTIVE: 403,
  CAPABILITY_ACCESS_REQUIRED: 403,
  POST_APPROVAL_ROOM_ISSUE_ACCESS_REQUIRED: 403,
  POST_APPROVAL_ROOM_ISSUE_SOURCE_UNAVAILABLE: 409,
  POST_APPROVAL_ROOM_ISSUE_DRAFT_CONFLICT: 409,
  POST_APPROVAL_ROOM_ISSUE_REPORT_SEALED: 409,
  POST_APPROVAL_ROOM_ISSUE_EVIDENCE_INVALID: 409,
  IDEMPOTENCY_KEY_REUSED: 409,
  POST_APPROVAL_ROOM_ISSUE_BODY_TOO_LARGE: 413,
  POST_APPROVAL_ROOM_ISSUE_MEDIA_TYPE_INVALID: 415,
  POST_APPROVAL_ROOM_ISSUE_COMMAND_FAILED: 500,
  POST_APPROVAL_ROOM_ISSUE_PROJECTION_INVALID: 500,
});
